
[all:vars]
ansible_ssh_private_key_file=/home/dbrun/dbRunPlaybooks/133275-1/hosts/PROD/ssh_keys/dbrun_133275_1_prd
ansible_python_interpreter=/home/snowop2/anaconda3/bin/python3
 
[na]
#HWVABCNASMDEV001
#ansiblehost
#nycinnycinp5.us.db.com
 
#[delegatedhosts]
#centos7-2 ansible_host=172.16.132.71
 
[na:vars]
ansible_user=3mtt
#ansible_host=10.0.0.57
ansible_python_interpreter=/usr/bin/python3
#ansible_host=localhost
#ansible_connection=local
#Cluster01 ansible_host=localhost ansible_connection=local
 
[win]
nycinnwfab1.us.db.com
 
#[win:vars]
#ansible_user=DBG\waghjai-a
#ansible_password=password123
#ansible_connection=winrm
#ansible_winrm_server_cert_validation=ignore
#ansible_winrm_transport=ntlm

